---
name: Fey-Test
version: 0.06
author:
  - 'Dave Rolsky, <autarch@urth.org>'
abstract: Test libraries for Fey distros
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DBI: 0
  File::Temp: 0
  List::MoreUtils: 0
  Test::More: 0
provides:
  Fey::Test:
    file: lib/Fey/Test.pm
    version: 0.06
  Fey::Test::Loader:
    file: lib/Fey/Test/Loader.pm
  Fey::Test::Pg:
    file: lib/Fey/Test/Pg.pm
  Fey::Test::SQLite:
    file: lib/Fey/Test/SQLite.pm
  Fey::Test::mysql:
    file: lib/Fey/Test/mysql.pm
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
